=== alphagov/submit-prototype-kit/schemas/form.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "uk.gov.gaap.submit.editor.form",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "heading": { "type": "string" },
    "phase": {
      "type": "string",
      "enum": ["alpha", "beta", "live"]
    },
    "organisations": {
      "type": "array",
      "items": { "$ref": "file:schemas/organisations.json" },
      "minItems": 0
    },
    "pages": {
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "anyOf": [
            { "$ref": "file:schemas/pages/start-page.json" },
            { "$ref": "file:schemas/pages/question.json" },
            { "$ref": "file:schemas/pages/check-your-answers.json" },
            { "$ref": "file:schemas/pages/bounce.json" },
            { "$ref": "file:schemas/pages/application-complete.json"}
          ]
        }
      }
    },
    "fields": {
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "anyOf": [
            { "$ref": "file:schemas/fields/checkboxes.json" },
            { "$ref": "file:schemas/fields/fieldset.json" },
            { "$ref": "file:schemas/fields/image.json" },
            { "$ref": "file:schemas/fields/list.json" },
            { "$ref": "file:schemas/fields/radio.json" },
            { "$ref": "file:schemas/fields/text.json" },
            { "$ref": "file:schemas/fields/textarea.json" }
          ]
        }
      }
    }
  },
  "required": ["name", "heading", "phase", "organisations", "pages", "fields"]
}

=== alphagov/submit-prototype-kit/examples/first-sale-fish.json
{
  "name": "first-sale-fish",
  "heading": "Register as a buyer of ‘first-sale’ fish",
  "phase": "alpha",
  "organisations": [
    {
      "name": "Marine Management Organisation",
      "organisation": "government-organisation:PB57",
      "website": "https://www.gov.uk/government/organisations/marine-management-organisation"
    }
  ],
  "pages": {
    "index": {
      "_id": 1,
      "pagetype": "start-page",
      "heading": "Ragister as a buyer of 'first-sale' fish",
      "guidance": "You need to register as a buyer of ‘first-sale’ fish if all of the following apply:\n* you’re buying fish that was landed in the UK\n* you’re buying fish or shellfish directly from a fishing vessel\n* you’re buying more than 30kg of fish per day\n\nYou don’t need to register if you buy fish from a: \n* designated auction site\n* merchant or wholesaler (this is ‘second sale’) \n* fish farm\n\nRegistering as a business\n-------------------------\n\nYou’ll need to upload documents to prove the address where you keep your records.\n\nRegistering as an individual\n----------------------------\n\nYou’ll need to prove your identity and the address where you keep your records. You might be able to do this by:\n* using GOV.UK Verify \n* uploading documents\n",
      "next": [ { "page": "where-will-you-buy" } ]
    },

    "where-will-you-buy": {
      "_id": 2,
      "pagetype": "question",
      "heading": "Where will you buy first-sale fish?",
      "fields":  ["country"],
      "next": [ {"page": "business-or-individual"} ]
    },

    "business-or-individual": {
      "_id": 3,
      "pagetype": "question",
      "heading": "Are you buying first-sale fish as a business or an individual?",
      "fields": [ "businessOrIndividual" ],
      "next": [
        { "page": "use-verify", "if": "data['businessOrIndividual'] == 'individual'" },
        { "page": "company-name", "if": "data['businessOrIndividual'] == 'business'" }
      ]
    },

    "use-verify": {
      "_id": 4,
      "pagetype": "question",
      "heading": "Do you want to prove your identity using GOV.UK Verify?",
      "guidance": "You can use GOV.UK Verify to prove your identity.\n\n\n\nIf you don’t use Verify, you’ll need to prove your identity with a scan or photo of either:\n\n* your current UK passport\n\n* your current UK or Isle of Man driving licence\n\n* a bank statement from the last 3 months\n\n* a utility bill from the last 3 months\n\n\n\nTo prove your address you will need a scan or photo of either:\n\n* your most recent council tax bill\n\n* a utility bill from the last 3 months (this cannot be the same as the document used to prove your identity)",
      "fields": ["useVerify"],
      "next": [
        { "page": "verify", "if": "data['useVerify'] == 'yes'" },
        { "page": "your-name" }
      ]
    },

    "verify": {
      "_id": 5,
      "pagetype": "interruption",
      "heading": "GOV.UK Verify",
      "body": "Verifying happens here.",
      "next": [ { "page": "location-of-records" } ]
    },

    "your-name": {
      "_id": 6,
      "pagetype": "question",
      "heading": "Your name",
      "fields": [ "name" ],
      "next": [ { "page": "date-of-birth" } ]
    },

    "date-of-birth": {
      "_id": 7,
      "pagetype": "question",
      "heading": "Your date of birth",
      "fields": [ "dateOfBirth" ],
      "next": [ { "page": "proof-of-identity" } ]
    },

    "proof-of-identity": {
      "_id": 8,
      "pagetype": "question",
      "heading": "Upload proof of identity",
      "guidance": "To prove your name, upload one of the following: \n\n* your current passport \n\n* a current UK or Isle of Man driving licence\n\n* a bank statement from the last 3 months \n\n* a utility bill from the last 3 months\n\n\n\nYou can use photographs or scans, as long as the image is clearly legible.\n\n\n\nFiles can be either JPG or PDF and no larger than 5mb.",
      "fields": [ "proofOfIdentity" ],
      "next": [ { "page": "location-of-records" } ]
    },

    "location-of-records": {
      "_id": 9,
      "pagetype": "question",
      "heading": "Where will you keep records of first-sale fish purchases?",
      "guidance": "To hold a first-sale licence you must keep records of each purchase of first-sale fish for 2 years.\n\nThese records must be shown to a marine officer on request.",
      "fields": [ "recordsAddress" ],
      "next": [ { "page": "proof-of-address" } ]
    },

    "proof-of-address": {
      "_id": 10,
      "pagetype": "question",
      "heading": "Upload proof of address",
      "_todo": "Variable substitution",
      "guidance": "To hold a licence you must prove you live at, or have access to:\n\n{{data.recordsAddress}}\n\n\n\nTo prove your address, upload a copy of either: \n\n* your current council tax bill (or equivalent)\n\n* utility bill from the last 3 months (must not be the same as the one used for proof of name)\n\n\n\nYou can use photographs or scans, as long as the image is clearly legible.\n\n\n\nFiles can be either JPG or PDF and no larger than 5mb.",
      "fields": [ "proofOfAddress" ],
      "next": [ { "page": "report-purchases-online" } ]
    },

    "report-purchases-online": {
      "_id": 11,
      "pagetype": "question",
      "heading": "Do you want to report purchases online?",
      "guidance": "You must submit sales notes for all purchases of first-sale fish.\n\nYou will need to give Email address if to report purchases of first-sale fish online.",
      "fields": [ "reportPurchases" ],
      "next": [
        { "page": "report-online", "if": "data['reportPurchases'] == 'online'" },
        { "page": "how-do-we-contact-you" }
      ]
    },

    "report-online": {
      "_id": 12,
      "pagetype": "question",
      "heading": "What's your email address?",
      "guidance": "Details on how to report purchases of first-sale fish will be sent with your licence.",
      "fields": [ "emailAddress" ],
      "next": [ { "page": "how-do-we-contact-you" } ]
    },

    "how-do-we-contact-you": {
      "_id": 13,
      "pagetype": "question",
      "heading": "How do you want to be contacted about your application?",
      "fields": [ "contactedAboutApplication" ],
      "fieldrefs": [ "emailAddress", "mobilePhoneNumber", "landlinePhoneNumber", "recordKeepingAddress" ],
      "next": [ 
        { "page": "contact-address", "if": "data['contactedAboutApplication'] == 'differentAddress'" },
        { "page": "check-your-answers" }
      ]
    },

    "contact-address": {
      "_id": 14,
      "pagetype": "question",
      "heading": "Contact address",
      "fields": [ "recordsAddress" ],
      "next": [ { "page": "check-your-answers" } ]
    },

    "check-your-answers": {
      "_id": 35,
      "pagetype": "check-your-answers",
      "heading": "Check your answers",
      "next": "confirmation"
    },

    "confirmation": {
      "_id": 37,
      "pagetype": "application-complete",
      "heading": "Application complete",
      "guidance": "Your reference number is {{ application number }}\n\n{% if ‘How do you want to be contacted about your application?’ ‘Email’ or ‘Phone’ %}\n\nWe have sent you a confirmation {{ email or text message }}. Licence applications take about 4 weeks to process."
    }

  },

  "fields": {
    "country": {
      "inputtype": "radio",
      "items": [
        { "label": "England", "value": "england" },
        { "label": "Northern Ireland", "value": "nothern-ireland" },
        { "label": "Scotland", "value": "scotland" },
        { "label": "Wales", "value": "wales" }
      ]
    },

    "businessOrIndividual": {
      "inputtype": "radio",
      "items": [
        { "label": "Business - Limited company, partership", "value": "business" },
        { "label": "Individual - sole trader or self-employed", "value": "individual" }
      ]
    },

    "useVerify": {
      "inputtype": "radio",
      "items": [
        { "label": "Yes", "value": "yes" },
        { "label": "No, upload documents to prove my identity", "value": "no" }
      ]
    },

    "name": {
      "inputtype": "text"
    },

    "dateOfBirth": {
      "inputtype": "date"
    },

    "proofOfIdentity": {
      "inputtype": "image"
    },

    "recordsAddress": {
      "_todo": "Address lookup",
      "label": "Address including postcode",
      "inputtype": "textarea"
    },

    "proofOfAddress": {
      "inputtype": "image"
    },

    "reportPurchases": {
      "inputtype": "radio",
      "items": [
        { "label": "Online", "value": "online" },
        { "label": "Post", "value": "post" }
      ]
    },

    "emailAddress": {
      "label": "Email address",
      "inputtype": "text"
    },

    "contactedAboutApplication": {
      "inputtype": "checkboxes",
      "items": [
        { "label": "Email", "value": "email", "fieldref": "emailAddress" },
        { "label": "Text message", "value": "textMessage", "fieldref": "mobilePhoneNumber" },
        { "label": "Phone", "value": "phone", "fieldref": "landlinePhoneNumber" },
        { "label": "Post at {{recordKeepingAddress}}", "_todo": "Variable substition", "value": "recordKeepingAddress" },
        { "label": "Post at a different address", "value": "differentAddress" }
      ]
    },

    "mobilePhoneNumber": {
      "label": "Phone number",
      "inputtype": "text"
    },

    "landlinePhoneNumber": {
      "label": "Phone number",
      "inputtype": "text"
    }

  }
}
